feat(deps): bump singer-sdk from 0.45.6 to 0.45.8 in the runtime-dependencies group (#253)
Bumps the runtime-dependencies group with 1 update:
[singer-sdk](https://github.com/meltano/sdk).

Updates `singer-sdk` from 0.45.6 to 0.45.8
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/releases">singer-sdk's
releases</a>.</em></p>
<blockquote>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/blob/main/CHANGELOG.md">singer-sdk's
changelog</a>.</em></p>
<blockquote>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/meltano/sdk/commit/b761e02d6a5272035c213037d2e59278b6662509"><code>b761e02</code></a>
chore: Release v0.45.8 (<a
href="https://redirect.github.com/meltano/sdk/issues/2972">#2972</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/d7c7a816b6d490519c3d737241b384ebed8058b0"><code>d7c7a81</code></a>
chore: Expose <code>singer_sdk._singerlib.Catalog</code> for typing-only
code</li>
<li><a
href="https://github.com/meltano/sdk/commit/3c116d877d3ed9bfcaa70d7a639876efa13614a4"><code>3c116d8</code></a>
fix: <code>AttributeError: object has no attribute
'_requests_session'</code> when acces...</li>
<li><a
href="https://github.com/meltano/sdk/commit/be10b376157f0b5778625cb8a9e55390413f1da9"><code>be10b37</code></a>
chore: pre-commit autoupdate (<a
href="https://redirect.github.com/meltano/sdk/issues/2971">#2971</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/104329932a808e683be46c3e338d2ff852891cba"><code>1043299</code></a>
fix: Consider <code>oneOf</code> schemas when checking for
<code>date</code> and <code>datetime</code> types (...</li>
<li><a
href="https://github.com/meltano/sdk/commit/7448d4eb35ccb08d2de0b2d4f3b7870d652a6d7c"><code>7448d4e</code></a>
chore: Minor tweak to the changelog</li>
<li><a
href="https://github.com/meltano/sdk/commit/38076a817700b640f997307c2b55bf30e9de3154"><code>38076a8</code></a>
chore: Release v0.45.7 (<a
href="https://redirect.github.com/meltano/sdk/issues/2969">#2969</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/27d3527d268aceef306bb5bb6d25c517abd385a4"><code>27d3527</code></a>
fix: Resolve <code>oneOf</code> schema references (<a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/0e7d31020c7285663e3e82fa57461dfcfe4f5be0"><code>0e7d310</code></a>
chore(deps): bump github/codeql-action from 3.28.14 to 3.28.15 in the
actions...</li>
<li><a
href="https://github.com/meltano/sdk/commit/6c1ac5fdd5f0d078252afaae1e110c1344f2751c"><code>6c1ac5f</code></a>
packaging: Add a <code>fallback-version</code> for hatch vcs (<a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/meltano/sdk/compare/v0.45.6...v0.45.8">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=singer-sdk&package-manager=pip&previous-version=0.45.6&new-version=0.45.8)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>